server:
  port: 8000
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    user:
      path: /user/**
      serviceId: userService
      strip-prefix: false
    submission:
      path: /submission/**
      serviceId: problemSubmissionService
      strip-prefix: false
  endpoints:
    routes:
      sensitive: false
    trace:
      sensitive: false


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/