server:
  port: 8000
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    user:
      path: /user/**
      serviceId: userService
      strip-prefix: false
    submission:
      path: /submission/**
      serviceId: problemSubmissionService
      strip-prefix: false
    leaderboard:
      path: /leaderboard/**
      serviceId: gamificationService
      strip-prefix: false
  sensitive-headers: Cookie, Set-Cookie

hystrix:
  command:
    problemSubmissionService:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
problemSubmissionService:
  ribbon:
    ReadTimeout: 10000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/