server:
  port: 8000
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    user:
      path: /user/**
      serviceId: userService
      strip-prefix: false
    submission:
      path: /submission/**
      serviceId: problemSubmissionService
      strip-prefix: false


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/